export const jobs = [
  {
    name: "Goarang Gupta",
    experience: "1 year",
    notice_period: "16 to 30 Days",
    current_ctc: "₹16LPA",
    worked_at: "Pitney Bowes",
    skills: [
      ".NET Framework",
      "MySQL",
      "Amazon Web Services",
      "Angular (Web Framework)",
      "Java (Programming Language)",
      "AI/ML",
      "Motion Graphic",
    ],
  },
  {
    name: "Afreen Taj",
    notice_period: "Immediately Available",
    skills: [
      ".NET Framework",
      "Cascading Style Sheets (CSS)",
      "CodeIgniter",
      "C (Programming Language)",
      "Github",
      "HTML5",
      "HyperText Markup Language (HTML)",
      "Java (Programming Language)",
      "JavaScript (Programming Language)",
      "Jupyter",
      "Jupyter Notebook",
      "Microsoft Visual Studio",
      "MySQL",
      "PHP (Scripting Language)",
      "Python (Programming Language)",
      "SQL (Programming Language)",
      "Asynchronous Javascript and XML (AJAX)",
      "Linux",
    ],
  },
  {
    name: "Manali Trivedi",
    experience: "2 years",
    notice_period: "Immediately Available",
    current_ctc: "₹2.64LPA",
    worked_at: ["Virtual Heights", "Sharvaya Infotech"],
    skills: [
      ".NET Framework",
      "Solidity (Programming Language)",
      "MySQL",
      "Python (Programming Language)",
      "AI/ML",
      "Motion Graphic",
      "React.js (Javascript Library)",
      "Cascading Style Sheets (CSS)",
      "Django (Web Framework)",
      "Docker (Software)",
      "HyperText Markup Language (HTML)",
      "Java (Programming Language)",
      "SQL (Programming Language)",
      "Ethereum",
      "Blockchain",
    ],
  },
  {
    name: "Abdul Samad Irfan",
    experience: "3.5 years",
    notice_period: "1 to 15 Days",
    current_ctc: "₹13.695LPA",
    worked_at: ["Neovest", "Educative", "Tricon Boston"],
    skills: [
      ".NET Framework",
      "Python (Programming Language)",
      "Azure Cloud Services",
      "AI/ML",
      "MySQL",
      "Docker (Software)",
      "JavaScript (Programming Language)",
      "C# (Programming Language)",
      "Django (Web Framework)",
      "C++ (Programming Language)",
      "Ethereum",
      "Motion Graphic",
      "Apache Kafka",
      "Amazon Web Services",
      "RabbitMQ",
    ],
  },
  {
    name: "Raja Rajeswari Saladi",
    notice_period: "Immediately Available",
    worked_at: "Virtusa Consulting",
    skills: [
      ".NET Framework",
      "AI/ML",
      "Motion Graphic",
      "C++ (Programming Language)",
      "Active Server Pages (ASP)",
      "Amazon Web Services",
      "Application Programming Interface (API)",
      "C (Programming Language)",
      "Java (Programming Language)",
      "JavaScript (Programming Language)",
      "MySQL",
      "Perceptron",
      "Puppeteer (Software)",
      "Python (Programming Language)",
      "React.js (Javascript Library)",
      "Web Applications",
      "Github",
      "Microsoft SQL Servers",
      "SQL (Programming Language)",
    ],
  },
  {
    name: "Pallavi Dasari",
    experience: "0.6 years",
    notice_period: "1 to 15 Days",
    current_ctc: "₹1000LPA",
    worked_at: ["Lasya Infotech", "Computer Society"],
    skills: [
      ".NET Framework",
      "Node.js (Javascript Library)",
      "Flutter (Software)",
      "Android SDK",
      "Azure Cloud Services",
      "Google Cloud Platform (GCP)",
      "Apache Hadoop",
      "Angular (Web Framework)",
      "Django (Web Framework)",
      "Tableau (Business Intelligence Software)",
      "AI/ML",
      "Blockchain",
      "Python (Programming Language)",
      "Pandas (Python Package)",
      "Plotly",
      "JavaScript Frameworks",
      "Java (Programming Language)",
      "Spring Framework",
      "Power BI",
      "DevOps",
      "Data Science",
      "SciPy",
      "R (Programming Language)",
      "Recommender Systems",
      "Prompt Engineering",
      "PL/SQL",
      "Oracle Platform Security Services",
      "Operating Systems",
      "NumPy (Python Package)",
      "MongoDB",
      "Microsoft Azure",
      "Matplotlib (Python Package)",
      "Jupyter Notebook",
      "HTML5",
      "Github",
      "Generative Artificial Intelligence",
      "Amazon Web Services",
      "C (Programming Language)",
      "HyperText Markup Language (HTML)",
      "JavaScript (Programming Language)",
      "Linux",
      "MySQL",
      "React.js (Javascript Library)",
      "React Native",
      "Scikit-Learn (Python Package)",
      "Spring Boot",
      "SQL (Programming Language)",
      "Application Programming Interface (API)",
      "C# (Programming Language)",
      "C++ (Programming Language)",
      "Dashboard",
      "Flux (React.js)",
    ],
  },
  {
    name: "Sadiq Yusuf Ilu",
    experience: "5.2 years",
    notice_period: "1 to 15 Days",
    current_ctc: "₹16.6LPA",
    worked_at: [
      "Galaxy itt",
      "Needle Technology",
      "Torre",
      "Alegra",
      "Sistema",
      "9Mobile",
    ],
    skills: [
      ".NET Framework",
      "Vue.js (Javascript Library)",
      "CI/CD pipelines",
      "Bash (Scripting Language)",
      "Java (Programming Language)",
      "JavaScript (Programming Language)",
      "Laravel",
      "MySQL",
      "PHP (Scripting Language)",
      "Play Framework",
      "Scala (Programming Language)",
      "Shopify",
      "DevOps",
      "Web Applications",
    ],
  },
  {
    name: "Tommi Kotikangas",
    experience: "6.1 years",
    notice_period: "Immediately Available",
    current_ctc: "₹95.45LPA",
    worked_at: ["Tech Briif", "Avanade", "Solteq Oy"],
    skills: [
      ".NET Framework",
      "React Native",
      "Azure Cloud Services",
      "React.js (Javascript Library)",
      "AI/ML",
      "Angular (Web Framework)",
      "Vue.js (Javascript Library)",
      "Visual Design",
    ],
  },
  {
    name: "Poorva Mandhanya",
    experience: "13 years",
    notice_period: "1 to 15 Days",
    current_ctc: "₹60LPA",
    worked_at: [
      "Simple Solutions",
      "Porter Airlines",
      "Insception",
      "Rogers",
      "Canadian Tire",
      "Dixie Bloor",
      "Allscripts",
      "Capella Web",
    ],
    skills: [
      ".NET Framework",
      "CI/CD pipelines",
      "React Native",
      "React.js (Javascript Library)",
      "AI/ML",
      "Amazon Web Services",
      "C# (Programming Language)",
      "Product Strategy",
      "Application Programming Interface (API)",
      "ASP.NET",
      "Asynchronous Javascript and XML (AJAX)",
      "Extensible Markup Language (XML)",
      "JQuery",
      "K2 Blackpearl",
      "Microsoft SharePoint",
      "SQL Server Integration Services (SSIS)",
      "Cascading Style Sheets (CSS)",
      "DevOps",
    ],
  },
  {
    name: "Pankaj Goswami",
    experience: "15 years",
    notice_period: "Immediately Available",
    current_ctc: "₹38LPA",
    worked_at: [
      "AzimuthGRC",
      "IndiaP2P",
      "Morningstar",
      "Adviser Logic",
      "StudyMantra Technologies",
      "PROTIVITI",
      "Alliance Infotech",
      "Wisethink Information",
      "KansysTechnologies",
    ],
    skills: [
      ".NET Framework",
      "Express.js (Javascript Library)",
      "Azure Cloud Services",
      "C# (Programming Language)",
      "Angular (Web Framework)",
      "ASP.NET",
      "Azure DevOps",
      "C (Programming Language)",
      "Docker (Software)",
      "JavaScript (Programming Language)",
      "Jenkins",
      "Kubernetes",
      "MongoDB",
      "MySQL",
      "Node.js (Javascript Library)",
      "SonarQube",
      "TypeScript",
      "Vue.js (Javascript Library)",
      "Amazon Web Services",
      "DevOps",
      "Nunit",
    ],
  },
];
